
name: Asana Actions

on:
  pull_request:
    types: [closed, opened]

jobs:
  task_completed:
    runs-on: ubuntu-20.04
    steps:
      - uses: everphone-gmbh/github-asana-action@c4d0c3aeb4768dc9dc45fb60b843c0510da20dd5
        if: github.event.pull_request.merged == true && github.event.action == 'closed'
        with:
          #change to the project's asana-pat in the project settings on github
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'complete-task'
          is-complete: true
      - uses: everphone-gmbh/github-asana-action@c4d0c3aeb4768dc9dc45fb60b843c0510da20dd5
        if: github.event.pull_request.merged == true && github.event.action == 'closed'
        with:
          #change to the project's asana-pat in the project settings on github
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'move-section'
          # change project & section according to board
          targets: '[{"project": "Design Project Plan", "section": "Release"}]'
  task_done:
    runs-on: ubuntu-20.04
    steps:
      - name: Set PR Number
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - uses: everphone-gmbh/github-asana-action@c4d0c3aeb4768dc9dc45fb60b843c0510da20dd5
        if: github.event.action != 'closed'
        with:
          #change to the project's asana-pat in the project settings on github
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'add-comment'
          #change base URL to the project's one
          text: 'Pull Request: https://github.com/Vitor-Bukovitz/asana-actions/pull/${{env.PR_NUMBER}}'
          is-pinned: true
      - uses: everphone-gmbh/github-asana-action@c4d0c3aeb4768dc9dc45fb60b843c0510da20dd5
        if: github.event.action != 'closed'
        with:
          #change to the project's asana-pat in the project settings on github
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'move-section'
          # change project & section according to board
          targets: '[{"project": "Design Project Plan", "section": "Done"}]'